### ISSUE TITLE
Scored Revisions to use test server

### ISSUE THREAD

**Issue by ToAruShiroiNeko** [he7d3r/mw-gadget-ScoredRevisions#1]
I would like to be able to use scored revisions with a test server. So for example I want to try how well En.Wikipedia model works on Simple English Wikipedia or Commons. It would not be a good idea to use the live system (ores) for this.

https://phabricator.wikimedia.org/T105834

**Comment by he7d3r** [comment]
See b2b0680c14284734bd348c6fe5fe4e33bc20c29c.
