### ISSUE TITLE
ScoredRevisions is not requesting scores for most edits

### ISSUE THREAD

**Issue by halfak** [he7d3r/mw-gadget-ScoredRevisions#8]
ORES responds with scores, but then ScoredRevisions doesn't make a request for the next 10 edits.

**Comment by halfak** [comment]
Observed on the [[en:Special:RecentChanges]]

**Comment by halfak** [comment]
I've been looking into this.  It seems that a variable is referenced strangely.  Even when I load 500 changes on Special:RecentChanges, this condition fails: https://github.com/he7d3r/mw-gadget-ScoredRevisions/blob/master/src/ScoredRevisions.js#L212

In my tests, it looks like there's only 16 items in `idsOnPage` after the first call.  I think that we'll want to provide a reference to all `idsOnPage` to scoreBatch so that it isn't accessing the variable from a weird scoping trick (what seems to happening now).

**Comment by halfak** [comment]
Woops.  Looks like we're only finding 16 revisions in total on the page!

**Comment by halfak** [comment]
OK!  I think I have figured out where the issue started.  It looks like the introduction of `conf.ScoredRevisionsEnableForPatrolledRevs` caused the issue.  On enwiki, ScoredRevisions is now only running on edits that create a page (and are therefor "unpatrolled").  So, it looks like we have three options, change the default behavior, make a custom configuration for enwiki or detect "patrolled" edits better.  I'll be looking into the latter.

**Comment by halfak** [comment]
Went looking and it seems there's no good option for detecting edits that are patrolled because we can't assume all edits are available to be patrolled.  I think I'm going to submit a PR with this change and see what @he7d3r thinks.

**Comment by he7d3r** [comment]
I'm pretty sure I replied to this but looks like I must have forgot to submit my comments. I was going to ask if it was related to the normal recent changes or the enhanced recent changes, which can be enabled on
https://en.wikipedia.org/wiki/Special:Preferences#mw-prefsection-rc
But since you figured out the cause, I merged https://github.com/he7d3r/mw-gadget-ScoredRevisions/pull/9. Thanks!

**Comment by halfak** [comment]
Considering this resolved for now.

**Comment by halfak** [comment]
FYI: I filed a feature request to make the "patrolled" status of an edit explicit.  See https://phabricator.wikimedia.org/T134689
